title: CCM BenchMate
url: https://qin-work.github.io/Benchmate_doc_ccm

# Theme configuration
remote_theme: just-the-docs/just-the-docs@main
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Site settings
theme: just-the-docs
collections:
  docs:
    output: true
